# This is a basic workflow to help you get started with Actions


name: CI

# Controls when the workflow will run

on:
	push:
		branches: [main]

	workflow_dispatch:

jobs:
	sync-to-hub:
	runs-on: ubuntu-latest
	steps:
	-uses: actions/checkout@v2
	with:
	fetch-depth: 0
	-name: Add remote
	env:
	HF: ${{ secrets.HF }}
	run: git remote add space https://huggingface.co/spaces/tdecae/demo1 
	-name: Push to hub
	env:
	HF: ${{ secrets.HF }}
	run: git push --force https://huggingface.co/spaces/tdecae/demo1 main

